// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {update} from '../models';
import {style} from '../models';
import {storyarc} from '../models';
import {chapter} from '../models';
import {character} from '../models';
import {location} from '../models';
import {novel} from '../models';
import {setting} from '../models';
import {preference} from '../models';
import {reader} from '../models';
import {timeline} from '../models';
import {llm} from '../models';
import {pattern} from '../models';
import {git} from '../models';
import {apperr} from '../models';
import {session} from '../models';
import {storage} from '../models';
import {config} from '../models';
import {writing} from '../models';
import {imp} from '../models';
import {skill} from '../models';
import {search} from '../models';

export function ApproveTool(arg1:string,arg2:boolean,arg3:string):Promise<void>;

export function CancelChat(arg1:string):Promise<void>;

export function CancelExtract(arg1:string):Promise<void>;

export function CancelExtractPattern(arg1:number):Promise<void>;

export function Chat(arg1:app.ChatInput):Promise<app.ChatResult>;

export function CheckUpdate(arg1:boolean):Promise<update.CheckResult>;

export function CompressContext(arg1:app.CompressInput):Promise<app.CompressResult>;

export function ComputeStyleStats(arg1:app.ComputeStyleStatsInput):Promise<style.Stats>;

export function CreateArcNode(arg1:number,arg2:app.CreateArcNodeInput):Promise<storyarc.ArcNode>;

export function CreateChapter(arg1:app.CreateChapterInput):Promise<chapter.Chapter>;

export function CreateCharacter(arg1:number,arg2:app.CreateCharacterInput):Promise<character.Character>;

export function CreateLocation(arg1:number,arg2:app.CreateLocationInput):Promise<location.Location>;

export function CreateNovel(arg1:app.CreateNovelInput):Promise<novel.Novel>;

export function CreateNovelSetting(arg1:number,arg2:app.CreateNovelSettingInput):Promise<setting.SettingItem>;

export function CreatePreference(arg1:number,arg2:app.CreatePreferenceInput):Promise<preference.PreferenceItem>;

export function CreateReaderPerspective(arg1:number,arg2:app.CreateReaderPerspectiveInput):Promise<reader.ReaderPerspective>;

export function CreateStoryArc(arg1:number,arg2:app.CreateStoryArcInput):Promise<storyarc.StoryArc>;

export function CreateStyleSample(arg1:app.CreateStyleSampleInput):Promise<style.Sample>;

export function CreateTimelineEntry(arg1:number,arg2:app.CreateTimelineEntryInput):Promise<timeline.TimelineEntry>;

export function DeleteArcNode(arg1:number,arg2:number):Promise<void>;

export function DeleteCharacter(arg1:number,arg2:number):Promise<void>;

export function DeleteCover(arg1:number):Promise<void>;

export function DeleteLocation(arg1:number,arg2:number):Promise<void>;

export function DeleteNovel(arg1:number):Promise<void>;

export function DeleteNovelSetting(arg1:number):Promise<void>;

export function DeletePreference(arg1:number):Promise<void>;

export function DeleteReaderPerspective(arg1:number,arg2:number):Promise<void>;

export function DeleteSkill(arg1:app.DeleteSkillInput):Promise<void>;

export function DeleteStoryArc(arg1:number,arg2:number):Promise<void>;

export function DeleteStyleSample(arg1:app.DeleteStyleSampleInput):Promise<void>;

export function DeleteTimelineEntry(arg1:number,arg2:number):Promise<void>;

export function DiscoverModels(arg1:string,arg2:string):Promise<Array<llm.ModelInfo>>;

export function DismissUpdate(arg1:string):Promise<void>;

export function ExportNovel(arg1:number,arg2:string):Promise<void>;

export function ExtractPattern(arg1:pattern.ExtractPatternInput):Promise<pattern.ExtractPatternResult>;

export function ExtractStyle(arg1:app.ExtractStyleInput):Promise<style.ExtractResult>;

export function GetAppConfig():Promise<Record<string, any>>;

export function GetArcNodes(arg1:number,arg2:number,arg3:number):Promise<Array<storyarc.ArcNode>>;

export function GetChapterPlans(arg1:number):Promise<Array<timeline.ChapterPlan>>;

export function GetChapters(arg1:number):Promise<Array<chapter.Chapter>>;

export function GetCharacterRelations(arg1:number):Promise<Array<character.CharacterRelation>>;

export function GetCharacters(arg1:number):Promise<Array<character.Character>>;

export function GetCommitFileList(arg1:number,arg2:string):Promise<app.CommitFileListResult>;

export function GetCommitLog(arg1:number,arg2:number,arg3:string):Promise<Array<git.CommitInfo>>;

export function GetContent(arg1:number,arg2:string):Promise<string>;

export function GetFileDiff(arg1:number,arg2:string,arg3:string):Promise<git.FileDiff>;

export function GetLLMConfig():Promise<llm.LLMConfigView>;

export function GetLocationRelations(arg1:number):Promise<Array<location.LocationRelation>>;

export function GetLocations(arg1:number):Promise<Array<location.Location>>;

export function GetMaxChapterNumber(arg1:number):Promise<number>;

export function GetModels():Promise<Array<llm.AvailableModel>>;

export function GetNovelSettings(arg1:number):Promise<app.SettingResult>;

export function GetNovels():Promise<Array<novel.Novel>>;

export function GetPlatform():Promise<Record<string, any>>;

export function GetPreferences(arg1:number):Promise<app.PreferenceResult>;

export function GetReaderPerspectives(arg1:number):Promise<Array<reader.ReaderPerspective>>;

export function GetRemoteSkillContent(arg1:string):Promise<apperr.Result_string_>;

export function GetSession(arg1:string):Promise<app.SessionDetail>;

export function GetSessionMessages(arg1:string):Promise<Array<session.Message>>;

export function GetSessions(arg1:app.GetSessionsInput):Promise<storage.PageResult_github_com_sigpanic_goink_app_SessionMeta_>;

export function GetSettings():Promise<config.AppSettings>;

export function GetStoryArcs(arg1:number):Promise<Array<storyarc.StoryArc>>;

export function GetStyleSample(arg1:number):Promise<style.Sample>;

export function GetTimelineEntries(arg1:number,arg2:number,arg3:number):Promise<Array<timeline.TimelineEntry>>;

export function GetVersion():Promise<string>;

export function GetWritingActivity(arg1:number):Promise<Array<writing.DailyActivity>>;

export function GetWritingStats():Promise<writing.WritingStats>;

export function ImportNovel(arg1:app.ImportNovelInput):Promise<imp.ImportResult>;

export function ImportWithLLM(arg1:app.ImportWithLLMInput):Promise<imp.ImportResult>;

export function Initialize(arg1:string):Promise<void>;

export function InstallRemoteSkill(arg1:app.InstallRemoteSkillInput):Promise<apperr.Result_struct____>;

export function IsInitialized():Promise<boolean>;

export function ListRemoteSkills(arg1:app.ListRemoteSkillsInput):Promise<apperr.Result_github_com_sigpanic_goink_internal_storage_PageResult_github_com_sigpanic_goink_internal_skill_remote_RemoteSkillMeta__>;

export function ListSkills(arg1:app.ListSkillsInput):Promise<Array<skill.SkillMeta>>;

export function ListSlashCommands(arg1:app.ListSlashCommandsInput):Promise<Array<app.SlashCommand>>;

export function ListStyleSamples(arg1:app.ListStyleSamplesInput):Promise<storage.PageResult_github_com_sigpanic_goink_internal_style_Sample_>;

export function PickAndImportNovel():Promise<imp.ImportResult>;

export function RebuildNovelIndex(arg1:number):Promise<void>;

export function SaveAvatar(arg1:Array<number>):Promise<void>;

export function SaveContent(arg1:app.SaveContentInput):Promise<void>;

export function SaveCover(arg1:number,arg2:Array<number>):Promise<void>;

export function SaveGitConfig(arg1:string,arg2:string):Promise<void>;

export function SaveLLMConfig(arg1:llm.LLMConfigView):Promise<void>;

export function SaveSettings(arg1:app.SaveSettingsInput):Promise<void>;

export function SaveUserName(arg1:string):Promise<void>;

export function SearchAll(arg1:number,arg2:string):Promise<Array<search.Result>>;

export function SetActiveNovel(arg1:app.SetActiveNovelInput):Promise<void>;

export function SetApprovalMode(arg1:string):Promise<void>;

export function SetLastSession(arg1:string):Promise<void>;

export function SetReasoningEffort(arg1:string):Promise<void>;

export function SetSelectedModel(arg1:string,arg2:string):Promise<void>;

export function TestConnection(arg1:app.TestConnectionInput):Promise<void>;

export function UpdateArcNode(arg1:number,arg2:number,arg3:app.UpdateArcNodeInput):Promise<void>;

export function UpdateChapterPlan(arg1:number,arg2:app.UpdateChapterPlanInput):Promise<void>;

export function UpdateChapterTitle(arg1:number,arg2:number,arg3:string):Promise<void>;

export function UpdateCharacter(arg1:number,arg2:number,arg3:app.UpdateCharacterInput):Promise<void>;

export function UpdateDataDir(arg1:string):Promise<void>;

export function UpdateLocation(arg1:number,arg2:number,arg3:app.UpdateLocationInput):Promise<void>;

export function UpdateNovel(arg1:number,arg2:app.UpdateNovelInput):Promise<novel.Novel>;

export function UpdateNovelSetting(arg1:number,arg2:number,arg3:app.UpdateNovelSettingInput):Promise<setting.SettingItem>;

export function UpdatePreference(arg1:number,arg2:number,arg3:app.UpdatePreferenceInput):Promise<preference.PreferenceItem>;

export function UpdateReaderPerspective(arg1:number,arg2:number,arg3:app.UpdateReaderPerspectiveInput):Promise<void>;

export function UpdateStoryArc(arg1:number,arg2:number,arg3:app.UpdateStoryArcInput):Promise<void>;

export function UpdateStyleSample(arg1:app.UpdateStyleSampleInput):Promise<style.Sample>;

export function UpdateTimelineEntry(arg1:number,arg2:number,arg3:app.UpdateTimelineEntryInput):Promise<void>;
