package llm

// Builtin 内置 provider 模板。APIKey 留空，运行时由用户配置注入。
var Builtin = map[string]Provider{
	"deepseek": {
		Name:        "DeepSeek",
		ChatURL:     "https://api.deepseek.com/v1/chat/completions",
		PlatformURL: "https://platform.deepseek.com",
		HelpText:    "使用邮箱或手机号注册。完成实名认证后，进入「API Keys」创建密钥。预付费模式，最低充值 ¥1。",
		Temperature: floatPtr(0.7),
		Models: []ModelInfo{
			{
				ID:               "deepseek-flash",
				Name:             "DeepSeek Flash",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  384_000,
				SupportsThinking: true,
				ReasoningLevels:  []string{"high", "max"},
				SupportsVision:   true,
			},
			{
				ID:               "deepseek-v4-pro",
				Name:             "DeepSeek V4 Pro",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  384_000,
				SupportsThinking: true,
				ReasoningLevels:  []string{"high", "max"},
				SupportsVision:   false,
			},
		},
		BuildRequest: nil,
	},
	"opencode": {
		Name:         "OpenCode Zen",
		ChatURL:      "https://opencode.ai/zen/v1/chat/completions",
		PlatformURL:  "https://opencode.ai/auth",
		HelpText:     "OpenCode Zen 是 opencode.ai 的按量付费网关，提供 DeepSeek/GLM/Kimi/MiniMax 等精选模型及多个免费模型（均兼容 OpenAI chat/completions）。在 opencode.ai/auth 注册、添加账单信息后复制 API Key 填入。OpenCode 网关要求携带 x-opencode-session 会话头与自定义 User-Agent，Goink 已自动处理，无需额外配置。模型列表随时变动，可用下方「自动发现模型」拉取最新。",
		Temperature:  floatPtr(0.7),
		BuildHeaders: opencodeBuildHeaders,
		Models: []ModelInfo{
			{
				ID:               "glm-5.3",
				Name:             "GLM-5.3",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "glm-5.3-flash",
				Name:             "GLM-5.3 Flash",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "glm-5.2",
				Name:             "GLM-5.2",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "glm-5.1",
				Name:             "GLM-5.1",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "kimi-k3",
				Name:             "Kimi K3",
				ContextWindow:    1_048_576,
				MaxOutputTokens:  131_072,
				SupportsThinking: true,
				ReasoningLevels:  []string{"max"},
				SupportsVision:   true,
			},
			{
				ID:               "kimi-k2.7-code",
				Name:             "Kimi K2.7 Code",
				ContextWindow:    262_144,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "kimi-k2.6",
				Name:             "Kimi K2.6",
				ContextWindow:    262_144,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "deepseek-v4-pro",
				Name:             "DeepSeek V4 Pro",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  384_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "deepseek-v4-flash",
				Name:             "DeepSeek V4 Flash",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  384_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "deepseek-v4-flash-vision-exp",
				Name:             "DeepSeek V4 Flash Vision Exp",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  384_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "minimax-m3",
				Name:             "MiniMax M3",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "minimax-m2.7",
				Name:             "MiniMax M2.7",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "big-pickle",
				Name:             "Big Pickle",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: false,
				SupportsVision:   false,
			},
			{
				ID:               "mimo-v2.5-free",
				Name:             "MiMo-V2.5 Free",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "ling-3.0-flash-fin-free",
				Name:             "Ling 3.0 Flash Fin Free",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: false,
				SupportsVision:   false,
			},
			{
				ID:               "nemotron-3-ultra-free",
				Name:             "Nemotron 3 Ultra Free",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: false,
				SupportsVision:   false,
			},
			{
				ID:               "nemotron-3.5-lightning-free",
				Name:             "Nemotron 3.5 Lightning Free",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: false,
				SupportsVision:   false,
			},
			{
				ID:               "qwen3.8-max",
				Name:             "Qwen3.8 Max",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  131_072,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "deepseek-v4.1-flash",
				Name:             "DeepSeek V4.1 Flash",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  384_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "deepseek-v4-flash-free",
				Name:             "DeepSeek V4 Flash Free",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  384_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "mimo-v2.6-flash-free",
				Name:             "MiMo-V2.6-Flash Free",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "ling-3.1-flash-free",
				Name:             "Ling 3.1 Flash Free",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: false,
				SupportsVision:   false,
			},
			{
				ID:               "space-bunny-free",
				Name:             "Space Bunny Free",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: false,
				SupportsVision:   false,
			},
			{
				ID:               "longcat-2.5-preview-free",
				Name:             "LongCat 2.5 Preview Free",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: false,
				SupportsVision:   false,
			},
			{
				ID:               "fledge-alpha-free",
				Name:             "Fledge Alpha Free",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: false,
				SupportsVision:   false,
			},
		},
	},
	"opencode-go": {
		Name:         "OpenCode Go",
		ChatURL:      "https://opencode.ai/zen/go/v1/chat/completions",
		PlatformURL:  "https://opencode.ai/auth",
		HelpText:     "OpenCode Go 是 opencode.ai 的订阅制服务（$10/月），覆盖 Kimi/GLM/DeepSeek/MiMo/Hy 等开源模型。在 opencode.ai/auth 注册并订阅 Go 后复制 API Key 填入。OpenCode Go 强制要求携带 x-opencode-session 会话头与自定义 User-Agent，Goink 已自动处理，无需额外配置。模型列表随订阅变动，可用下方「自动发现模型」拉取最新。",
		Temperature:  floatPtr(0.7),
		BuildHeaders: opencodeBuildHeaders,
		Models: []ModelInfo{
			{
				ID:               "kimi-k3",
				Name:             "Kimi K3",
				ContextWindow:    1_048_576,
				MaxOutputTokens:  131_072,
				SupportsThinking: true,
				ReasoningLevels:  []string{"max"},
				SupportsVision:   true,
			},
			{
				ID:               "glm-5.3",
				Name:             "GLM-5.3",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "deepseek-v4-pro",
				Name:             "DeepSeek V4 Pro",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  384_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "deepseek-v4-flash",
				Name:             "DeepSeek V4 Flash",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  384_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "deepseek-v4.1-flash",
				Name:             "DeepSeek V4.1 Flash",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  384_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "deepseek-v4-flash-vision-exp",
				Name:             "DeepSeek V4 Flash Vision Exp",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  384_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "glm-5.3-flash",
				Name:             "GLM-5.3 Flash",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "kimi-k2.7-code",
				Name:             "Kimi K2.7 Code",
				ContextWindow:    262_144,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "glm-5.2",
				Name:             "GLM-5.2",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "glm-5.1",
				Name:             "GLM-5.1",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "kimi-k2.6",
				Name:             "Kimi K2.6",
				ContextWindow:    262_144,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "longcat-2.0",
				Name:             "LongCat-2.0",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "mimo-v2.5",
				Name:             "MiMo-V2.5",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "mimo-v2.5-pro",
				Name:             "MiMo-V2.5 Pro",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "hy4-preview",
				Name:             "Hy4 preview",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "hy3",
				Name:             "Hy3",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "mimo-v2.6-pro",
				Name:             "MiMo-V2.6-Pro",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "mimo-v2.6-flash",
				Name:             "MiMo-V2.6-Flash",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "deepseek-flash",
				Name:             "DeepSeek Flash",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  384_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "hy3-preview",
				Name:             "Hy3 preview",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "longcat-2.5-preview-free",
				Name:             "LongCat 2.5 Preview Free",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: false,
				SupportsVision:   false,
			},
			{
				ID:               "space-bunny-free",
				Name:             "Space Bunny Free",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: false,
				SupportsVision:   false,
			},
		},
	},
	"doubao": {
		Name:        "Doubao",
		ChatURL:     "https://ark.cn-beijing.volces.com/api/v3/chat/completions",
		PlatformURL: "https://console.volcengine.com/ark/",
		HelpText:    "注册火山引擎并实名认证，进入火山方舟控制台。① 在「API 密钥管理」创建 API Key；② 在「开通管理」开通所需模型，每个模型有试用额度。",
		Temperature: floatPtr(0.1),
		Models: []ModelInfo{
			{
				ID:               "doubao-seed-evolving",
				Name:             "Seed Evolving",
				ContextWindow:    1_048_576,
				MaxOutputTokens:  262_144,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "doubao-seed-2-1-pro-260915",
				Name:             "Seed 2.1 Pro",
				ContextWindow:    1_048_576,
				MaxOutputTokens:  262_144,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "doubao-seed-2-1-lite-260915",
				Name:             "Seed 2.1 Lite",
				ContextWindow:    1_048_576,
				MaxOutputTokens:  262_144,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "doubao-seed-character-260628",
				Name:             "Seed Character",
				ContextWindow:    128_000,
				MaxOutputTokens:  32_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
		},
	},
	"qwen": {
		Name:         "Qwen",
		ChatURL:      "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions",
		PlatformURL:  "https://platform.qianwenai.com",
		HelpText:     "注册后在「工作台 → API Key 管理」创建密钥。新用户有免费额度，API 地址统一使用 dashscope.aliyuncs.com，无需区分地域。如使用阿里云百炼平台，需自行将上方 Chat URL 替换为百炼地址。",
		Temperature:  floatPtr(0.7),
		BuildRequest: qwenBuildRequest,
		Models: []ModelInfo{
			{
				ID:               "qwen3.8-max",
				Name:             "Qwen3.8 Max",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  131_072,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "qwen3.8-flash",
				Name:             "Qwen3.8 Flash",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  131_072,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "qwen3.7-plus",
				Name:             "Qwen3.7 Plus",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  131_072,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "qwen3.7-flash",
				Name:             "Qwen3.7 Flash",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  131_072,
				SupportsThinking: true,
				SupportsVision:   true,
			},
		},
	},
	"zhipu": {
		Name:        "GLM",
		ChatURL:     "https://open.bigmodel.cn/api/paas/v4/chat/completions",
		PlatformURL: "https://open.bigmodel.cn",
		HelpText:    "手机号或微信注册。注册后点击「控制台」→「API Keys」→「新建」创建密钥。注册赠送体验额度。",
		Temperature: floatPtr(1.0),
		Models: []ModelInfo{
			{
				ID:               "glm-5.3",
				Name:             "GLM-5.3",
				ContextWindow:    1_048_576,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				ReasoningLevels:  []string{"low", "high", "max"},
				SupportsVision:   false,
			},
			{
				ID:               "glm-5.3-flash",
				Name:             "GLM-5.3-Flash",
				ContextWindow:    1_048_576,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				ReasoningLevels:  []string{"low", "high", "max"},
				SupportsVision:   true,
			},
			{
				ID:               "glm-5.3-flashx",
				Name:             "GLM-5.3-FlashX",
				ContextWindow:    1_048_576,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				ReasoningLevels:  []string{"low", "high", "max"},
				SupportsVision:   true,
			},
			{
				ID:               "glm-5.2",
				Name:             "GLM-5.2",
				ContextWindow:    1_048_576,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "glm-5.1",
				Name:             "GLM-5.1",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "glm-5",
				Name:             "GLM-5",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "glm-5-turbo",
				Name:             "GLM-5-Turbo",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "glm-4.7",
				Name:             "GLM-4.7",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "glm-4.7-flashx",
				Name:             "GLM-4.7-FlashX",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "glm-4.7-flash",
				Name:             "GLM-4.7 Flash",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
		},
		BuildRequest: nil,
	},
	"minimax": {
		Name:         "MiniMax",
		ChatURL:      "https://api.minimaxi.com/v1/chat/completions",
		PlatformURL:  "https://platform.minimaxi.com",
		HelpText:     "手机号注册。赠送 ¥15 体验金。点击控制台 →「接口管理」→「创建 API Key」获取密钥。按量付费需在「余额」页面充值。",
		Temperature:  floatPtr(1.0),
		BuildRequest: minimaxBuildRequest,
		Models: []ModelInfo{
			{
				ID:               "MiniMax-M3",
				Name:             "MiniMax M3",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
		},
	},
	"mimo": {
		Name:         "MiMo",
		ChatURL:      "https://api.xiaomimimo.com/v1/chat/completions",
		PlatformURL:  "https://platform.xiaomimimo.com",
		HelpText:     "手机号注册。在控制台左侧「邀请有礼」输入邀请码领取 ¥10 体验金（有效期 40 天），然后在「API Keys」创建密钥。",
		Temperature:  floatPtr(1.0),
		BuildHeaders: mimoBuildHeaders,
		Models: []ModelInfo{
			{
				ID:               "mimo-v2.6-pro",
				Name:             "MiMo V2.6 Pro",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "mimo-v2.6-flash",
				Name:             "MiMo V2.6 Flash",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
		},
		BuildRequest: nil,
	},
	"moonshot": {
		Name:         "Kimi",
		ChatURL:      "https://api.moonshot.cn/v1/chat/completions",
		PlatformURL:  "https://platform.kimi.com",
		HelpText:     "手机号或微信登录。在控制台「API Key 管理」创建密钥。新用户赠送 ¥15 体验金，初始 RPM=3。累计充值 ¥50 升 Tier 1（RPM=200）。",
		BuildRequest: moonshotBuildRequest,
		Models: []ModelInfo{
			{
				ID:               "kimi-k3",
				Name:             "Kimi K3",
				ContextWindow:    1_048_576,
				MaxOutputTokens:  1_048_576,
				SupportsThinking: true,
				ReasoningLevels:  []string{"max"},
				SupportsVision:   true,
			},
			{
				ID:               "kimi-k2.7-code",
				Name:             "Kimi K2.7 Code",
				ContextWindow:    262_144,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "kimi-k2.7-code-highspeed",
				Name:             "Kimi K2.7 Code HighSpeed",
				ContextWindow:    262_144,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "kimi-k2.6",
				Name:             "Kimi K2.6",
				ContextWindow:    262_144,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
		},
	},
}
